// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertesting.protos;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * AccountDetails contains the state of an account.
 */
public final class AccountDetails extends Message {

  public static final Integer DEFAULT_QUEUE = 0;
  public static final Integer DEFAULT_MAX_QUEUE = 0;

  /**
   * queue is the number of messages waiting at the server.
   */
  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer queue;

  /**
   * max_queue is the maximum number of messages that the server will
   * queue for this account.
   */
  @ProtoField(tag = 2, type = UINT32, label = REQUIRED)
  public final Integer max_queue;

  public AccountDetails(Integer queue, Integer max_queue) {
    this.queue = queue;
    this.max_queue = max_queue;
  }

  private AccountDetails(Builder builder) {
    this(builder.queue, builder.max_queue);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AccountDetails)) return false;
    AccountDetails o = (AccountDetails) other;
    return equals(queue, o.queue)
        && equals(max_queue, o.max_queue);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = queue != null ? queue.hashCode() : 0;
      result = result * 37 + (max_queue != null ? max_queue.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AccountDetails> {

    public Integer queue;
    public Integer max_queue;

    public Builder() {
    }

    public Builder(AccountDetails message) {
      super(message);
      if (message == null) return;
      this.queue = message.queue;
      this.max_queue = message.max_queue;
    }

    /**
     * queue is the number of messages waiting at the server.
     */
    public Builder queue(Integer queue) {
      this.queue = queue;
      return this;
    }

    /**
     * max_queue is the maximum number of messages that the server will
     * queue for this account.
     */
    public Builder max_queue(Integer max_queue) {
      this.max_queue = max_queue;
      return this;
    }

    @Override
    public AccountDetails build() {
      checkRequiredFields();
      return new AccountDetails(this);
    }
  }
}
