// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertesting.protos;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.FIXED64;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class Download extends Message {

  public static final ByteString DEFAULT_FROM = ByteString.EMPTY;
  public static final Long DEFAULT_ID = 0L;
  public static final Long DEFAULT_RESUME = 0L;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString from;

  @ProtoField(tag = 2, type = FIXED64, label = REQUIRED)
  public final Long id;

  @ProtoField(tag = 3, type = INT64)
  public final Long resume;

  public Download(ByteString from, Long id, Long resume) {
    this.from = from;
    this.id = id;
    this.resume = resume;
  }

  private Download(Builder builder) {
    this(builder.from, builder.id, builder.resume);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Download)) return false;
    Download o = (Download) other;
    return equals(from, o.from)
        && equals(id, o.id)
        && equals(resume, o.resume);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = from != null ? from.hashCode() : 0;
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (resume != null ? resume.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Download> {

    public ByteString from;
    public Long id;
    public Long resume;

    public Builder() {
    }

    public Builder(Download message) {
      super(message);
      if (message == null) return;
      this.from = message.from;
      this.id = message.id;
      this.resume = message.resume;
    }

    public Builder from(ByteString from) {
      this.from = from;
      return this;
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder resume(Long resume) {
      this.resume = resume;
      return this;
    }

    @Override
    public Download build() {
      checkRequiredFields();
      return new Download(this);
    }
  }
}
