// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertestingwithouttor.protos;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * AccountCreated is the reply to a NewAccount request.
 */
public final class AccountCreated extends Message {

  @ProtoField(tag = 1, label = REQUIRED)
  public final AccountDetails details;

  public AccountCreated(AccountDetails details) {
    this.details = details;
  }

  private AccountCreated(Builder builder) {
    this(builder.details);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AccountCreated)) return false;
    return equals(details, ((AccountCreated) other).details);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = details != null ? details.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<AccountCreated> {

    public AccountDetails details;

    public Builder() {
    }

    public Builder(AccountCreated message) {
      super(message);
      if (message == null) return;
      this.details = message.details;
    }

    public Builder details(AccountDetails details) {
      this.details = details;
      return this;
    }

    @Override
    public AccountCreated build() {
      checkRequiredFields();
      return new AccountCreated(this);
    }
  }
}
