// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertestingwithouttor.protos;

import com.squareup.wire.Message;

/**
 * Fetch is a request to fetch a message. It may result in either a Fetched, or
 * ServerAnnounce message. (Or none at all if no messages are pending.)
 */
public final class Fetch extends Message {

  public Fetch() {
  }

  private Fetch(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Fetch;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Fetch> {

    public Builder() {
    }

    public Builder(Fetch message) {
      super(message);
    }

    @Override
    public Fetch build() {
      return new Fetch(this);
    }
  }
}
