// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertestingwithouttor.protos;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;

public final class UploadReply extends Message {

  public static final Long DEFAULT_RESUME = 0L;

  @ProtoField(tag = 1, type = INT64)
  public final Long resume;

  public UploadReply(Long resume) {
    this.resume = resume;
  }

  private UploadReply(Builder builder) {
    this(builder.resume);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UploadReply)) return false;
    return equals(resume, ((UploadReply) other).resume);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = resume != null ? resume.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<UploadReply> {

    public Long resume;

    public Builder() {
    }

    public Builder(UploadReply message) {
      super(message);
      if (message == null) return;
      this.resume = message.resume;
    }

    public Builder resume(Long resume) {
      this.resume = resume;
      return this;
    }

    @Override
    public UploadReply build() {
      return new UploadReply(this);
    }
  }
}
