// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./pond.proto
package systems.obscure.servertesting.protos;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ServerAnnounce is a special type of reply to a Fetch request. The message
 * comes from the server, rather than from another client and it's intended to
 * be used for announcements from the server operator to all or some users.
 */
public final class ServerAnnounce extends Message {

  @ProtoField(tag = 1, label = REQUIRED)
  public final Message message;

  public ServerAnnounce(Message message) {
    this.message = message;
  }

  private ServerAnnounce(Builder builder) {
    this(builder.message);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ServerAnnounce)) return false;
    return equals(message, ((ServerAnnounce) other).message);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = message != null ? message.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ServerAnnounce> {

    public Message message;

    public Builder() {
    }

    public Builder(ServerAnnounce message) {
      super(message);
      if (message == null) return;
      this.message = message.message;
    }

    public Builder message(Message message) {
      this.message = message;
      return this;
    }

    @Override
    public ServerAnnounce build() {
      checkRequiredFields();
      return new ServerAnnounce(this);
    }
  }
}
